version: '3'
services:
  engine:
    build:
      context: .
      dockerfile: dockerfiles/engine/Dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - PLAYER_1_NAME=bot1
      - PLAYER_2_NAME=bot2
      - PLAYER_1_DNS=bot1:50051
      - PLAYER_2_DNS=bot2:50051

  bot1:
    build:
      context: .
      dockerfile: dockerfiles/python_skeleton/Dockerfile
    volumes:
      - ./logs/bot1:/usr/src/app/logs
    depends_on:
      - engine
    expose:
      - "50051"

  bot2:
    build:
      context: .
      dockerfile: dockerfiles/python_skeleton2/Dockerfile
    volumes:
      - ./logs/bot2:/usr/src/app/logs
    depends_on:
      - engine
    expose:
      - "50052"
