# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokerbot_pb2 as pokerbot__pb2


class PokerBotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckReady = channel.unary_unary(
                '/pokerbot.PokerBotService/CheckReady',
                request_serializer=pokerbot__pb2.ReadyCheckRequest.SerializeToString,
                response_deserializer=pokerbot__pb2.ReadyCheckResponse.FromString,
                )
        self.RequestAction = channel.unary_unary(
                '/pokerbot.PokerBotService/RequestAction',
                request_serializer=pokerbot__pb2.ActionRequest.SerializeToString,
                response_deserializer=pokerbot__pb2.ActionResponse.FromString,
                )
        self.EndGame = channel.unary_unary(
                '/pokerbot.PokerBotService/EndGame',
                request_serializer=pokerbot__pb2.EndGameRequest.SerializeToString,
                response_deserializer=pokerbot__pb2.EndGameResponse.FromString,
                )


class PokerBotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokerBotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckReady': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckReady,
                    request_deserializer=pokerbot__pb2.ReadyCheckRequest.FromString,
                    response_serializer=pokerbot__pb2.ReadyCheckResponse.SerializeToString,
            ),
            'RequestAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAction,
                    request_deserializer=pokerbot__pb2.ActionRequest.FromString,
                    response_serializer=pokerbot__pb2.ActionResponse.SerializeToString,
            ),
            'EndGame': grpc.unary_unary_rpc_method_handler(
                    servicer.EndGame,
                    request_deserializer=pokerbot__pb2.EndGameRequest.FromString,
                    response_serializer=pokerbot__pb2.EndGameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokerbot.PokerBotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PokerBotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokerbot.PokerBotService/CheckReady',
            pokerbot__pb2.ReadyCheckRequest.SerializeToString,
            pokerbot__pb2.ReadyCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokerbot.PokerBotService/RequestAction',
            pokerbot__pb2.ActionRequest.SerializeToString,
            pokerbot__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pokerbot.PokerBotService/EndGame',
            pokerbot__pb2.EndGameRequest.SerializeToString,
            pokerbot__pb2.EndGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
