# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokerbot_pb2 as pokerbot__pb2


class PokerBotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadyCheck = channel.unary_unary(
                '/poker.PokerBot/ReadyCheck',
                request_serializer=pokerbot__pb2.ReadyCheckRequest.SerializeToString,
                response_deserializer=pokerbot__pb2.ReadyCheckResponse.FromString,
                )
        self.RequestAction = channel.unary_unary(
                '/poker.PokerBot/RequestAction',
                request_serializer=pokerbot__pb2.ActionRequest.SerializeToString,
                response_deserializer=pokerbot__pb2.ActionResponse.FromString,
                )
        self.EndRound = channel.unary_unary(
                '/poker.PokerBot/EndRound',
                request_serializer=pokerbot__pb2.EndRoundMessage.SerializeToString,
                response_deserializer=pokerbot__pb2.EndRoundResponse.FromString,
                )


class PokerBotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadyCheck(self, request, context):
        """Initial readiness check at the beginning of the match.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAction(self, request, context):
        """Requests an action from a player.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRound(self, request, context):
        """Notifies the end of a round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokerBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadyCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadyCheck,
                    request_deserializer=pokerbot__pb2.ReadyCheckRequest.FromString,
                    response_serializer=pokerbot__pb2.ReadyCheckResponse.SerializeToString,
            ),
            'RequestAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAction,
                    request_deserializer=pokerbot__pb2.ActionRequest.FromString,
                    response_serializer=pokerbot__pb2.ActionResponse.SerializeToString,
            ),
            'EndRound': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRound,
                    request_deserializer=pokerbot__pb2.EndRoundMessage.FromString,
                    response_serializer=pokerbot__pb2.EndRoundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poker.PokerBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PokerBot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadyCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poker.PokerBot/ReadyCheck',
            pokerbot__pb2.ReadyCheckRequest.SerializeToString,
            pokerbot__pb2.ReadyCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poker.PokerBot/RequestAction',
            pokerbot__pb2.ActionRequest.SerializeToString,
            pokerbot__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poker.PokerBot/EndRound',
            pokerbot__pb2.EndRoundMessage.SerializeToString,
            pokerbot__pb2.EndRoundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
