# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokerbot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epokerbot.proto\x12\x08pokerbot\"(\n\x11ReadyCheckRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"#\n\x12ReadyCheckResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"Z\n\rActionRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\x12\n\ngame_clock\x18\x02 \x01(\x02\x12\x10\n\x08\x62\x61nkroll\x18\x03 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\"F\n\x0e\x41\x63tionResponse\x12$\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x14.pokerbot.ActionType\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x03\"%\n\x0e\x45ndGameRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"\x1e\n\x0f\x45ndGameResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08*6\n\nActionType\x12\x08\n\x04\x46OLD\x10\x00\x12\x08\n\x04\x43\x41LL\x10\x01\x12\t\n\x05\x43HECK\x10\x02\x12\t\n\x05RAISE\x10\x03\x32\xe4\x01\n\x0fPokerBotService\x12I\n\nCheckReady\x12\x1b.pokerbot.ReadyCheckRequest\x1a\x1c.pokerbot.ReadyCheckResponse\"\x00\x12\x44\n\rRequestAction\x12\x17.pokerbot.ActionRequest\x1a\x18.pokerbot.ActionResponse\"\x00\x12@\n\x07\x45ndGame\x12\x18.pokerbot.EndGameRequest\x1a\x19.pokerbot.EndGameResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokerbot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTIONTYPE']._serialized_start=342
  _globals['_ACTIONTYPE']._serialized_end=396
  _globals['_READYCHECKREQUEST']._serialized_start=28
  _globals['_READYCHECKREQUEST']._serialized_end=68
  _globals['_READYCHECKRESPONSE']._serialized_start=70
  _globals['_READYCHECKRESPONSE']._serialized_end=105
  _globals['_ACTIONREQUEST']._serialized_start=107
  _globals['_ACTIONREQUEST']._serialized_end=197
  _globals['_ACTIONRESPONSE']._serialized_start=199
  _globals['_ACTIONRESPONSE']._serialized_end=269
  _globals['_ENDGAMEREQUEST']._serialized_start=271
  _globals['_ENDGAMEREQUEST']._serialized_end=308
  _globals['_ENDGAMERESPONSE']._serialized_start=310
  _globals['_ENDGAMERESPONSE']._serialized_end=340
  _globals['_POKERBOTSERVICE']._serialized_start=399
  _globals['_POKERBOTSERVICE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
